### ISSUE TITLE
Create new user interaction layer

### ISSUE THREAD

**Issue by FrederikTobner** [jksevend/tobot-engine#33]
We need to add a new user interaction layer, because writing code in c++ sucks ass. We could either write a CLI tool to generate the code for the user or transpile the code from a different language. We could for example use ANTLR for that purpose and transpile files written in our own domain specific language, that is close to c++ to .cpp and .h files.
Another possiblity is to use a language that integrates well with C++, like C# or Lua.
We could of course also create our own scripting language based on Lox / Cellox

## CLI

tobot add scene / game-object / text etc.
tobot create example
tobot build (--target 3DS)
tobot test
tobot analyze
tobot profiler

## Editor

A seperate editor would be another solution for creating tobot applications.
The editor could utilize the cli tool in the background.
The editor could support  another domain specific scripting language or / and c++.

## Lua

Another possibilty would be to use [lua](https://www.lua.org/start.html) as the scripting language, because it is easily integrates with c++ and is profen scripting language.

## ANTLR / LLVM

From a scripting language with a clike syntax we could generate the code in c++. Similar to how Unity utilizes C#.
The transpiler could utilize the cli tool in the background to create the application.

## C#

C# offers interoperabilty with C++ and offers  good performance. Additionally it is widely used in and outside of game development. Therefor using it would make propably make sense as well.

## Custom Lox based scripting language

We could build our own scripting language using lox / Cellox as a template and call the scripts in our c++ example.
We would need to provide some native functions for that purpose.

## Carbon

Even though carbon is not even released yet we could use it as our scripting language latter as well.
If carbon is ready when we create our sscripting layer we should evaluate this possiblity again, even though it propably won't be that easy to use compared to the other alternatives (excluding c++ - nothing is harder than this piece of shit 🥴)

## TODO:

Add a new cli module / library with some basic commands and define architecure.
Add a graphical editor that utilizes either our CLI tools or the other tobot libraries.

## To define

* Shall we use cmake in the backgound or provide our own build system.
* What internal libraries does the CLI need ?
* What language do we want to use as long term solution? Scripting languages are a nice idea on paper to implement the game logic, because the dont require to recompile the project everytime we make a change. But on the other hand they tend to be error prone and errors are harder to fix compared to most other langauges. I feel like C# would be the best solution here because it is faily easy to use, but still comes with most of the benefits of C++ / Carbon. The only downside is the performance but I think we can neglect that. We could take a look at Hazel and their way of using C#.

**Comment by jksevend** [comment]
Maybe we can wait and make carbon the integrated language

**Comment by FrederikTobner** [comment]
I with the part about making a cli because creating such a transpiler would be long term project. But maybe we create something like that in the future and stick with the cli approach for the next 10 years or so.

**Comment by FrederikTobner** [comment]
Added ideas to the tobot-engine architecture repo
