### ISSUE TITLE
Improving architecture using libraries

### ISSUE THREAD

**Issue by FrederikTobner** [jksevend/tobot-engine#37]
We have added libraries as the new top level organizational unit for our code. Therefor we need to adapt our architecture and think about what we want to implement as a seperate library and what should stay in the tobot_engine library.

Possible new libraries / modules:
* Camera
* Widgets / In-Game GUI
* Networking
* Serialization 
* Deserialization
* Particle system
* Collider system
* Lighting systems
* Tile manager
* Input manager
* Low-level code / Platform independence layer (contains platform specific functions for the file system, network layers) - kinda like SDL for the stuff it does not already provide (like the folder check in logger.cpp)
* Automatic memory management (garbage collection)
* Testing framework for tobot applications
* Physics (Material manager)
* AI (path finding, Decision making using scoring functions)
* Transpiler / Scripting layer
* etc.

We can of course implement these libraries later, but we should at least define the structure we want to have in the future.

**Comment by jksevend** [comment]
I will follow with an updated architecture image today, maybe containing ways on how to split up engine

**Comment by jksevend** [comment]
I also thought about when shipping out profiling as a devtool to have some kind UI with it. Maybe we could even use Flutter Desktop for that and connect our code through writing plugins to let flutter comunicate with our cpp profiling module

**Comment by FrederikTobner** [comment]
Or we use the internal widget system of the engine for creating the UI
