### ISSUE TITLE
Rename namespaces

### ISSUE THREAD

**Issue by FrederikTobner** [jksevend/tobot-engine#42]
The way our namespaces are named is not designed in way that differentiates between the libraries.
Maybe we can change it to something like

`TobotEngine::Core` / `Tobot::Core`
`TobotTooling::Logging`
`TobotTooling::Profiling`
...

I really dont like having the logger in `Tobot::Utilities` ...

**Comment by jksevend** [comment]
I would suggest something like `Tobot::<Library>::<Unit>` for example `Tobot::Tooling::Logger` or (for now) `Tobot::Engine::TobotApplication`

**Comment by FrederikTobner** [comment]
I will adapt the tooling lib in that regard

**Comment by jksevend** [comment]
Isnt this done by now @FrederikTobner

**Comment by FrederikTobner** [comment]
> Isnt this done by now @FrederikTobner 

I think it is.
